/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test2;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PANACHAITECHAPHAISAL
 */
public class SendForm extends javax.swing.JFrame {

    private Connection con = null;
    private ResultSet rs = null;
    private PreparedStatement pst = null;

    public SendForm() {
        initComponents();
        con = Test2.connectDB();
        combouser();
    }

    public void combouser() {
        try {
            String sql = "select * from myusername";
            pst = con.prepareCall(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("UserName");
                nameuser.addItem(name);
            }
        } catch (Exception e) {
        }
    }

    public void showUsercombobook() {
        try {
            String sql = "select * from  `history`  WHERE `IDName`='" + nameuser.getSelectedItem().toString() + "' and`Status`='Lend'";
            pst = con.prepareCall(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("BookName");
                Book.addItem(name);
            }
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameuser = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Book = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Username");

        nameuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameuserActionPerformed(evt);
            }
        });

        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("SendBook");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Send Book");

        jButton2.setText("Comfirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameuser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Book, 0, 213, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton2)
                        .addGap(38, 38, 38)
                        .addComponent(jButton3)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameuser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Book, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Book.removeAllItems();
        showUsercombobook();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String sql = "SELECT * FROM `history` WHERE IDName='" + nameuser.getSelectedItem().toString() + "'"
                    + "and BookName='" + Book.getSelectedItem().toString() + "'and `Status`='Lend'";
            pst = con.prepareCall(sql);
            rs = pst.executeQuery();
            String send = "";
            while (rs.next()) {
                send = rs.getString("TimetoSend");
            }
            SimpleDateFormat formatter2 = new SimpleDateFormat("EE MMM dd HH:mm:ss z yyyy");

            Date data2Send = formatter2.parse(send);

            Calendar c = Calendar.getInstance();

// set the calendar to start of today
// and get that as a Date
            Date today = c.getTime();
// test your condition
            if (today.before(data2Send)) {
                String sqlUpdate = "update`history` set `Fine`='0' ,`Status`='Send' where IDName='" + nameuser.getSelectedItem().toString() + "'"
                        + "and BookName='" + Book.getSelectedItem().toString() + "'and `Status`='Lend' ";
                pst = con.prepareStatement(sqlUpdate);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Haven't Fine :D", "Complete", JOptionPane.INFORMATION_MESSAGE);

                String sql2 = "update myusername set UserStats=? where UserName='" + nameuser.getSelectedItem().toString() + "'";
                pst = con.prepareStatement(sql2);
                pst.setString(1, "OK");
                pst.execute();

            } else {
                String sqlUpdate = "update`history` set `Fine`='30' ,`Status`='Send' where IDName='" + nameuser.getSelectedItem().toString() + "'"
                        + "and BookName='" + Book.getSelectedItem().toString() + "'and `Status`='Lend'";
                pst = con.prepareStatement(sqlUpdate);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Have Fine 30 Bath ", "Complete", JOptionPane.INFORMATION_MESSAGE);

                String sql1 = "select * from myusername where UserName='" + nameuser.getSelectedItem().toString() + "'";
                pst = con.prepareStatement(sql1);
                rs = pst.executeQuery();
                int add5 = 0;
                if (rs.next()) {
                    add5 = rs.getInt("UserFine");
                }

                String sql2 = "update myusername set UserFine=? ,UserStats=? where UserName='" + nameuser.getSelectedItem().toString() + "'";
                pst = con.prepareStatement(sql2);
                add5 += 30;
                pst.setString(1, "" + add5);
                pst.setString(2, "Have Fine");
                pst.execute();

            }
            String sql3 = "update history set ReturnDate='" + today + "' where IDName='" + nameuser.getSelectedItem().toString() + "'"
                    + "and BookName='" + Book.getSelectedItem().toString() + "'and `Status`='Send' ";
            pst = con.prepareStatement(sql3);
            pst.execute();

            String sql4 = "select * from booklist where bookname='" + Book.getSelectedItem().toString() + "'";
            pst = con.prepareStatement(sql4);
            rs = pst.executeQuery();
            int add = 0;
            if (rs.next()) {
                add = rs.getInt("NumofBook");
            }

            String sql5 = "update booklist set NumofBook=? where bookname='"+ Book.getSelectedItem().toString() + "'";
            pst = con.prepareStatement(sql5);
            add +=1;
            pst.setString(1, "" + add);
            pst.execute();
            
            MainForm mainform = new MainForm();
            mainform.setVisible(true);
            close();

        } catch (SQLException ex) {
            Logger.getLogger(SendForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(SendForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MainForm mainform = new MainForm();
        mainform.setVisible(true);
        close();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nameuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendForm().setVisible(true);
            }
        });
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Book;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> nameuser;
    // End of variables declaration//GEN-END:variables
}
